# Use custom docker image. https://www.gitpod.io/docs/config-docker
image: ghcr.io/sagemath/sage/sage-docker-gitpod-standard-with-targets:dev

# Start up tasks. https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Setup
    before: |
      # Setup ssh key for authentication with trac
      ## In order to use this, generate a new key with `ssh-keygen -f tempkey` and save the private key to gitpod `gp env PRIVATE_SSH_KEY="$(<tempkey)"` (or by following https://www.gitpod.io/docs/environment-variables#using-the-account-settings)
      ## then follow https://doc.sagemath.org/html/en/developer/trac.html#linking-your-public-key-to-your-trac-account to register the public key with trac.
      mkdir -p ~/.ssh
      echo $PRIVATE_SSH_KEY | sed 's/\(-----\(BEGIN\|END\) OPENSSH PRIVATE KEY-----\)/\n\1\n/g' > ~/.ssh/id_rsa
      sed -i '/^$/d' ~/.ssh/id_rsa
      chmod 600 ~/.ssh/id_rsa
      unset PRIVATE_SSH_KEY
      ssh-keyscan -H trac.sagemath.org >> ~/.ssh/known_hosts
      SAGE_LOCAL=/workspace/sage/local
      if [ -d "$SAGE_LOCAL" ]; then
        echo "Prebuild init script has been run. Running "make" again in case the build had timed out."
        # First set the installation records to the same mtime so that no rebuilds due to dependencies
        # among these packages are triggered.  This is from .github/workflows/extract-sage-local.sh
        dummy="$SAGE_LOCAL"/var/lib/sage/installed/.dummy
        if [ -f "$dummy" ]; then
            touch "$dummy"
            for tree in "$SAGE_LOCAL" "$SAGE_LOCAL"/var/lib/sage/venv*; do
                inst="$tree"/var/lib/sage/installed
                if [ -d "$inst" ]; then
                    # -r is --reference; the macOS version of touch does not accept the long option.
                    (cd "$inst" && touch -r "$dummy" .dummy *)
                fi
            done
        fi
        unset SAGE_LOCAL
        # Now run make.
        MAKE='make -j24' timeout 51m make build V=0
      fi
    init: |
      # Only /workspace is preserved during build.
      # If the Docker image contains a built SAGE_LOCAL, move it into the workspace.
      if [ ! -d local -a -d $HOME/sage-local ]; then
        mv $HOME/sage-local local
      fi
      rm -Rf $HOME/sage-local
      ln -sf $(pwd)/local $HOME/sage-local
      # Setup trac repo
      git remote add trac git@trac.sagemath.org:sage.git -t master
      git remote set-url --push trac git@trac.sagemath.org:sage.git

      # Start build
      ./bootstrap
      ./configure --enable-editable --enable-download-from-upstream-url --prefix=$HOME/sage-local --with-sage-venv
      ## Gitpod has a timeout of 1h, so make sure we are below this to ensure that the prebuild is always successful
      MAKE='make -j24' timeout 51m make build V=0 || echo "(ignoring error)"
    env:
      SAGE_NUM_THREADS: 8

# Preinstalled VS Code extensions. https://www.gitpod.io/docs/vscode-extensions
vscode:
  extensions:
    - ms-pyright.pyright
    - ms-python.python
    - trond-snekvik.simple-rst
    - lextudio.restructuredtext
    - streetsidesoftware.code-spell-checker
    - ms-toolsai.jupyter

# https://www.gitpod.io/docs/prebuilds#github-specific-configuration
github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
