# Start up tasks. https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Setup
    before: |
      # Setup ssh key for authentication with trac
      ## In order to use this, generate a new key with `ssh-keygen -f tempkey` and save the private key to gitpod `gp env PRIVATE_SSH_KEY="$(<tempkey)"` (or by following https://www.gitpod.io/docs/environment-variables#using-the-account-settings)
      ## then follow https://doc.sagemath.org/html/en/developer/trac.html#linking-your-public-key-to-your-trac-account to register the public key with trac.
      mkdir ~/.ssh
      echo $PRIVATE_SSH_KEY > ~/.ssh/id_rsa
      chmod 600 ~/.ssh/id_rsa
    init: |
      # Setup trac repo
      git remote add trac git@trac.sagemath.org:sage.git -t master
      git remote set-url --push trac git@trac.sagemath.org:sage.git

      # Install system packages
      sudo apt-get update
      ## Needed for bootstrap
      sudo apt-get install -y gettext
      ## From dockerfile
      sudo apt-get install -y --no-install-recommends gfortran gcc g++ libstdc++-9-dev sudo openssl
      sudo apt-get install -y wget build-essential automake m4 dpkg-dev python libssl-dev git rdfind
      ## Recommended by ./configure
      ### We do not install tox, since it pulls in javascript-common which does not install for some reason
      sudo apt-get install -y libflint-arb-dev libbrial-dev libbrial-groebner-dev libcdd-dev libcdd-tools ecl libec-dev eclib-tools fflas-ffpack flintqs libgc-dev gfan libgiac-dev xcas libgsl-dev libiml-dev lcalc liblfunction-dev libhomfly-dev libopenblas-dev palp pari-gp2c libpari-dev pari-doc pari-elldata pari-galdata pari-galpol pari-seadata libppl-dev ppl-dev python3 libpython3-dev python3-distutils r-base-dev r-cran-lattice librw-dev libsuitesparse-dev libsymmetrica2-dev sympow tachyon libzmq3-dev libzn-poly-dev python3-venv libgf2x-dev cliquer libcliquer-dev gmp-ecm libecm-dev glpk-utils libglpk-dev libbraiding-dev liblrcalc-dev libm4rie-dev libmpc-dev libmpfi-dev libmpfr-dev nauty libntl-dev libplanarity-dev planarity 
      ## Homebrew has more up-to-date package versions
      ### We do not install ecl from brew, since this breaks the build of maxima
      brew update
      brew upgrade
      brew install arb flint fplll pari pari-elldata pari-galdata pari-galpol pari-seadata tox
      ### Give prio to brew over system packages
      export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
      
      # Configure 
      ## Gitpod sets PIP_USER: yes by default, which leads to problems during build (e.g pip not being installed in the venv)
      unset PIP_USER
      ## Gitpod installs pyenv by default, and sage's pip install targets the pyenv python for some reason
      pyenv global system

      # Start build
      ./bootstrap
      ./configure -enable-editable
      MAKE='make -j8' make build
    env: 
      SAGE_NUM_THREADS: 4

# Preinstalled VS Code extensions. https://www.gitpod.io/docs/vscode-extensions
vscode:
  extensions:
    - ms-pyright.pyright
    - ms-python.python
    - lextudio.restructuredtext
    - streetsidesoftware.code-spell-checker
