# Use custom docker image. https://www.gitpod.io/docs/config-docker
image:
  file: docker/.gitpod.Dockerfile

# Start up tasks. https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Setup
    before: |
      # Setup ssh key for authentication with trac
      ## In order to use this, generate a new key with `ssh-keygen -f tempkey` and save the private key to gitpod `gp env PRIVATE_SSH_KEY="$(<tempkey)"` (or by following https://www.gitpod.io/docs/environment-variables#using-the-account-settings)
      ## then follow https://doc.sagemath.org/html/en/developer/trac.html#linking-your-public-key-to-your-trac-account to register the public key with trac.
      mkdir -p ~/.ssh
      echo $PRIVATE_SSH_KEY | sed 's/\(-----\(BEGIN\|END\) OPENSSH PRIVATE KEY-----\)/\n\1\n/g' > ~/.ssh/id_rsa
      sed -i '/^$/d' ~/.ssh/id_rsa
      chmod 600 ~/.ssh/id_rsa
      unset PRIVATE_SSH_KEY
      # Disable pyenv since it would interfere with sages build process
      pyenv shell --unset
    init: |
      # Reuse non-Python packages compiled during the docker build
      mv /home/gitpod/sage-local /workspace/sage-local

      # Setup trac repo
      git remote add trac git@trac.sagemath.org:sage.git -t master
      git remote set-url --push trac git@trac.sagemath.org:sage.git

      # Disable pyenv since it would interfere with sages build process
      pyenv shell --unset

      # Start build
      ./bootstrap
      ./configure --enable-editable --prefix=/workspace/sage-local --with-sage-venv
      ## Gitpod has a timeout of 1h, so make sure we are below this to ensure that the prebuild is always successful
      MAKE='make -j16' timeout 55m make build V=0 || true
    env: 
      SAGE_NUM_THREADS: 4

# Preinstalled VS Code extensions. https://www.gitpod.io/docs/vscode-extensions
vscode:
  extensions:
    - ms-pyright.pyright
    - ms-python.python
    - trond-snekvik.simple-rst
    - lextudio.restructuredtext
    - streetsidesoftware.code-spell-checker
    - ms-toolsai.jupyter
