queries:
  - exclude: py/call/wrong-named-class-argument
  - exclude: py/call/wrong-number-class-arguments
  - exclude: py/unsafe-cyclic-import
extraction:
  python:
    python_setup:
      version: 3
