queries:
  - exclude: py/call/wrong-named-class-argument
  - exclude: py/call/wrong-number-class-arguments
  - exclude: py/unsafe-cyclic-import
path_classifiers:
  imports_only:
    - "**/all.py"
    - "**/*catalog*.py"
extraction:
  python:
    python_setup:
      version: 3
