queries:
  - exclude: py/call/wrong-named-class-argument
  - exclude: py/call/wrong-number-class-arguments
  - exclude: py/unsafe-cyclic-import
path_classifiers:
  imports_only:
    - "**/all.py"
    - "**/*catalog*.py"
    - "**/species/library.py"
    - "**/categories/basic.py"
    - "**/combinat/ribbon.py"
    - "**/interacts/geometry.py"
    - "**/matroids/advanced.py"
    - "**/matroids/named_matroids.py"
    - "**/modular/congroup.py"
    - "**/quadratic_forms/quadratic_form__mass.py"
extraction:
  python:
    python_setup:
      version: 3
