#!/usr/bin/env bash

if [ "$SAGE_LOCAL" = "" ]; then
   echo "SAGE_LOCAL undefined ... exiting";
   echo "Maybe run 'sage -sh'?"
   exit 1
fi

echo "Deleting old SQLAlchemy installs"
rm -rf "$SAGE_LOCAL/lib/python/site-packages/SQLAlchemy*"

# Install SQLAlchemy
cd src
sage-setup.py install --record=$FILELIST
