#!/usr/bin/env bash

if [ "$SAGE_PREFIX" = "" ]; then
   echo "SAGE_PREFIX undefined ... exiting";
   echo "Maybe run 'sage -sh'?"
   exit 1
fi

# Apply patches.  See SPKG.txt for information about what each patch
# does.
( echo "include spkg.mk" | sage-dist-make - patch-stamp ) || exit $?

cd src

python setup.py build
if [ $? -ne 0 ]; then
    echo >&2 "Error building IPython."
    exit 1
fi

echo "Removing old version of IPython..."
# FIXME: use unstage (later)
rm -rf "$SAGE_PREFIX/lib/python/site-packages/IPython"
if [ $? -ne 0 ]; then
    echo >&2 "Error deleting previous version"
    exit 1
fi

sage-setup.py install --record=$FILELIST

if [ $? -ne 0 ]; then
    echo >&2 "Error installing IPython"
    exit 1
fi
