[build-system]
requires = ["setuptools>=61.2"]
build-backend = "setuptools.build_meta"

[project]
name = "sage-conf"
description = "Sage: Open Source Mathematics Software: Configuration module for the SageMath library"
readme = "README.rst"
license = {text = "GNU General Public License (GPL) v3 or later"}
authors = [{name = "The Sage Developers", email = "sage-support@googlegroups.com"}]
urls = {Homepage = "https://www.sagemath.org"}
dynamic = ["version"]

[project.scripts]
sage-config = "sage_conf:_main"

[tool.setuptools]
packages = ["_sage_conf"]
py-modules = ["sage_conf"]
script-files = ["bin/sage-env-config"]
include-package-data = false

[tool.setuptools.dynamic]
version = {file = ["VERSION.txt"]}
