Default: FORCE
	g++ -o prova main.cpp weisfeiler_lehman.cpp -lm -std=c++0x
debug: FORCE
	g++ -o prova main.cpp weisfeiler_lehman.cpp -lm -std=c++0x -g -DDEBUG
optimized: FORCE
	g++ -o prova main.cpp weisfeiler_lehman.cpp -lm -std=c++0x -O2
superoptimized: FORCE
	g++ -o prova main.cpp weisfeiler_lehman.cpp -lm -std=c++0x -O3
debugoptimized: FORCE
	g++ -o prova main.cpp weisfeiler_lehman.cpp -lm -std=c++0x -g -DDEBUG -O3
FORCE:

