#!/usr/bin/env bash

if [ -z "$SAGE_LOCAL" ]; then
    echo >&2 "SAGE_LOCAL undefined ... exiting"
    echo >&2 "Maybe run 'sage --sh'?"
    exit 1
fi


# Apply patches.
( echo "include spkg.mk" | sage-dist-make - patch-stamp ) || exit $?

cd src
# Now build and install.
cp Setup.py setup.py
sage-setup.py build

if [ $? -ne 0 ]; then
    echo >&2 "Error building gdmodule."
    exit 1
fi

sage-setup.py install --record=$FILELIST

if [ $? -ne 0 ]; then
    echo >&2 "Error installing gdmodule."
    exit 1
fi
