#!/usr/bin/env bash

if [ "$SAGE_LOCAL" = "" ]; then
   echo "SAGE_LOCAL undefined ... exiting";
   echo "Maybe run 'sage -sh'?"
   exit 1
fi

#Remove old version
# FIXME: HACK
rm -rf "$SAGE_LOCAL"/lib/python/site-packages/Pygments-*

# Apply patches
echo "Patching Pygments..."
( echo "include spkg.mk" | sage-dist-make - patch-stamp ) || exit $?

#Install new version
cd src

sage-setup.py install --record=$FILELIST

if [ $? -ne 0 ]; then
   echo "Error installing Pygments."
   exit 1
fi
