175,0
T,LatMod,LatModElt,0
A,LatMod,11,Form,Module,Discriminant,Norm,Scale,Definite,Diagonal,GenusSymbols,ZForms,AutoIsomData,Auto
A,LatModElt,2,Parent,Element
V,LatMod,1
S,ZBasis,A Z-basis for the module M,0,1,0,0,0,0,0,0,0,361,,82,-38,-38,-38,-38,-38
S,LocalBasis,A basis of a free module that coincides with M at the prime ideal p,0,2,0,0,0,0,0,0,0,217,,0,0,361,,82,-38,-38,-38,-38,-38
S,Print,internal,0,2,0,0,1,0,0,0,0,298,,0,0,LatModElt,,-38,-38,-38,-38,-38,-38
S,Parent,internal,0,1,0,0,0,0,0,0,0,LatModElt,,LatMod,-38,-38,-38,-38,-38
S,Vector,internal,0,1,0,0,0,0,0,0,0,LatModElt,,362,-38,-38,-38,-38,-38
S,Element,internal,0,1,0,0,0,0,0,0,0,LatModElt,,362,-38,-38,-38,-38,-38
S,Eltseq,internal,0,1,0,0,0,0,0,0,0,LatModElt,,82,-38,-38,-38,-38,-38
S,eq,internal,0,2,0,0,0,0,0,0,0,LatModElt,,0,0,LatModElt,,36,-38,-38,-38,-38,-38
S,Hash,internal,0,1,0,0,0,0,0,0,0,LatModElt,,148,-38,-38,-38,-38,-38
S,+,internal,0,2,0,0,0,0,0,0,0,LatModElt,,0,0,LatModElt,,LatModElt,-38,-38,-38,-38,-38
S,-,internal,0,2,0,0,0,0,0,0,0,LatModElt,,0,0,LatModElt,,LatModElt,-38,-38,-38,-38,-38
S,*,internal,0,2,0,0,0,0,0,0,0,-45,,0,0,LatModElt,,LatModElt,-38,-38,-38,-38,-38
S,*,internal,0,2,0,0,0,0,0,0,0,LatModElt,,0,0,-45,,LatModElt,-38,-38,-38,-38,-38
S,/,internal,0,2,0,0,0,0,0,0,0,-45,,0,0,LatModElt,,LatModElt,-38,-38,-38,-38,-38
S,InnerProduct,"The inner product (v,w)",0,2,0,0,0,0,0,0,0,LatModElt,,0,0,LatModElt,,-45,-38,-38,-38,-38,-38
S,Norm,The norm of v,0,1,0,0,0,0,0,0,0,LatModElt,,-45,-38,-38,-38,-38,-38
S,IsZero,Returns true if v is the zero vector,0,1,0,0,0,0,0,0,0,LatModElt,,36,-38,-38,-38,-38,-38
S,Matrix,The matrix of the sequence of lattice elements,1,0,1,82,0,LatModElt,1,0,0,0,0,0,0,0,82,,-34,-38,-38,-38,-38,-38
S,Print,internal,0,2,0,0,1,0,0,0,0,298,,0,0,LatMod,,-38,-38,-38,-38,-38,-38
S,IsCoercible,internal,0,2,0,0,0,0,0,0,0,-1,,0,0,LatMod,,36,-1,-38,-38,-38,-38
S,in,internal,0,2,0,0,0,0,0,0,0,LatMod,,0,0,LatModElt,,36,-38,-38,-38,-38,-38
S,in,internal,0,2,0,0,0,0,0,0,0,LatMod,,0,0,192,,36,-38,-38,-38,-38,-38
S,LatticeModule,The lattice consisting of the module M and the bilinear form F,0,2,0,0,0,0,0,0,0,-34,,0,0,361,,LatMod,-38,-38,-38,-38,-38
S,LatticeModule,The free lattice with bilinear form F,0,1,0,0,0,0,0,0,0,-34,,LatMod,-38,-38,-38,-38,-38
S,LatticeModule,The lattice generated by the rows of B with bilinear form F,0,2,0,0,0,0,0,0,0,-34,,0,0,-34,,LatMod,-38,-38,-38,-38,-38
S,GramMatrix,The Gram matrix of the sequence S (or the rows of S) in the ambient space of L,0,2,0,0,0,0,0,0,0,-34,,0,0,LatMod,,-34,-38,-38,-38,-38,-38
S,GramMatrix,The Gram matrix of the sequence S (or the rows of S) in the ambient space of L,0,2,0,0,0,0,0,0,0,82,,0,0,LatMod,,-34,-38,-38,-38,-38,-38
S,GramMatrix,The Gram matrix of a minimal set of generators of L,0,1,0,0,0,0,0,0,0,LatMod,,-34,82,-38,-38,-38,-38
S,IsOrthogonal,Returns true if the lattice L was created as an orthogonal lattice,0,1,0,0,0,0,0,0,0,LatMod,,36,-38,-38,-38,-38,-38
S,IsHermitian,Returns true if the lattice L was created as an hermitian lattice,0,1,0,0,0,0,0,0,0,LatMod,,36,-38,-38,-38,-38,-38
S,Involution,The involution to the hermitian/ortohogonal space of L,0,1,0,0,0,0,0,0,0,LatMod,,175,-38,-38,-38,-38,-38
S,InternalConjugate,internal,0,2,0,0,0,0,0,0,0,-34,,0,0,LatMod,,-34,-38,-38,-38,-38,-38
S,FixedField,The fixed field of the involution of L,0,1,0,0,0,0,0,0,0,LatMod,,-9,-38,-38,-38,-38,-38
S,InnerProductMatrix,Returns the inner product matrix of the lattice L,0,1,0,0,0,0,0,0,0,LatMod,,-34,-38,-38,-38,-38,-38
S,Module,Returns the module strucure of L,0,1,0,0,0,0,0,0,0,LatMod,,361,-38,-38,-38,-38,-38
S,IsFree,Tests if the lattice L is a free module,0,1,0,0,0,0,0,0,0,LatMod,,36,-38,-38,-38,-38,-38
S,IsZero,Tests if the lattice L is zero,0,1,0,0,0,0,0,0,0,-1,,36,-38,-38,-38,-38,-38
S,IsDefinite,"Whether a number field lattice is definite. If so, an element such that the rescaled lattice is totally positive definite",0,1,0,0,0,0,0,0,0,LatMod,,36,216,-38,-38,-38,-38
S,IsPositiveDefinite,Tests if the lattice L or its ambient space is (totally) positive definite,0,1,0,0,0,0,0,0,0,LatMod,,36,-38,-38,-38,-38,-38
S,IsTotallyPositiveDefinite,Tests if the lattice L or its ambient space is (totally) positive definite,0,1,0,0,0,0,0,0,0,LatMod,,36,-38,-38,-38,-38,-38
S,ChangeRing,Return a lattice over the integers if L is over QNF(),0,2,0,0,0,0,0,0,0,319,,0,0,LatMod,,164,-38,-38,-38,-38,-38
S,CanChangeRing,Tests if the lattice L can be written over the ring R,0,2,0,0,0,0,0,0,0,-44,,0,0,LatMod,,36,164,-38,-38,-38,-38
S,ChangeRing,The lattice L over ring R,0,2,0,0,0,0,0,0,0,-44,,0,0,LatMod,,164,-38,-38,-38,-38,-38
S,Discriminant,The discriminant ideal of L,0,1,0,0,0,0,0,0,0,LatMod,,324,-38,-38,-38,-38,-38
S,ZBasis,A Z-basis for the lattice L,0,1,0,0,0,0,0,0,0,LatMod,,82,-38,-38,-38,-38,-38
S,AbsoluteBasis,A Z-basis for the lattice L,0,1,0,0,0,0,0,0,0,LatMod,,82,-38,-38,-38,-38,-38
S,Generators,A sequence of elements that generate L over its base ring,0,1,0,0,0,0,0,0,0,LatMod,,82,-38,-38,-38,-38,-38
S,LocalBasis,A basis of a free module that coincides with L at the prime ideal p,0,2,0,0,0,0,0,0,0,217,,0,0,LatMod,,82,-38,-38,-38,-38,-38
S,BasisMatrix,Returns Matrix(Basis(Module(L))),0,1,0,0,0,0,0,0,0,LatMod,,-34,-38,-38,-38,-38,-38
S,BaseRing,The base ring of the lattice L,0,1,0,0,0,0,0,0,0,LatMod,,215,-38,-38,-38,-38,-38
S,NumberField,The number field the lattice is over,0,1,0,0,0,0,0,0,0,LatMod,,27,-38,-38,-38,-38,-38
S,Rank,The rank or dimension of the lattice L,0,1,0,0,0,0,0,0,0,LatMod,,148,-38,-38,-38,-38,-38
S,Dimension,The rank or dimension of the lattice L,0,1,0,0,0,0,0,0,0,LatMod,,148,-38,-38,-38,-38,-38
S,Degree,The degree of the lattice L,0,1,0,0,0,0,0,0,0,LatMod,,148,-38,-38,-38,-38,-38
S,IsFull,Returns true if the lattice is of full rank,0,1,0,0,0,0,0,0,0,LatMod,,36,-38,-38,-38,-38,-38
S,eq,internal,0,2,0,0,0,0,0,0,0,LatMod,,0,0,LatMod,,36,-38,-38,-38,-38,-38
S,subset,internal,0,2,0,0,0,0,0,0,0,LatMod,,0,0,LatMod,,36,-38,-38,-38,-38,-38
S,Perp,"The lattice {x in L1 | (x,L2) = 0}",0,2,0,0,0,0,0,0,0,LatMod,,0,0,LatMod,,LatMod,-38,-38,-38,-38,-38
S,SubConstructor,The sublattice of L generated by RHS,0,2,0,0,0,0,0,0,0,303,,0,0,LatMod,,LatMod,-38,-38,-38,-38,-38
S,ExtConstructor,The lattice generated by L and RHS,0,2,0,0,0,0,0,0,0,303,,0,0,LatMod,,LatMod,-38,-38,-38,-38,-38
S,ZLattice,The lattice with a Z-basis of L,0,1,0,0,0,0,0,0,0,LatMod,,164,175,-38,-38,-38,-38
S,QuoConstructor,The quotient of L by RHS,0,2,0,0,0,0,0,0,0,303,,0,0,LatMod,,107,175,-38,-38,-38,-38
S,*,internal,0,2,0,0,0,0,0,0,0,LatMod,,0,0,-45,,LatMod,-38,-38,-38,-38,-38
S,*,internal,0,2,0,0,0,0,0,0,0,LatMod,,0,0,324,,LatMod,-38,-38,-38,-38,-38
S,*,internal,0,2,0,0,0,0,0,0,0,324,,0,0,LatMod,,LatMod,-38,-38,-38,-38,-38
S,*,internal,0,2,0,0,0,0,0,0,0,-34,,0,0,LatMod,,LatMod,-38,-38,-38,-38,-38
S,+,internal,0,2,0,0,0,0,0,0,0,LatMod,,0,0,LatMod,,LatMod,-38,-38,-38,-38,-38
S,meet,internal,0,2,0,0,0,0,0,0,0,LatMod,,0,0,LatMod,,LatMod,-38,-38,-38,-38,-38
S,Rescale,Rescale the form of L with the scalar a,0,2,0,0,0,0,0,0,0,-45,,0,0,LatMod,,LatMod,-38,-38,-38,-38,-38
S,IsIntegral,Returns true if and only if L is integral (with respect to its bilinear or sesquilinear form),0,1,0,0,0,0,0,0,0,LatMod,,36,-38,-38,-38,-38,-38
S,IsIntegral,Returns true if and only if L is integral (with respect to its bilinear or sesquilinear form),0,2,0,0,0,0,0,0,0,217,,0,0,LatMod,,36,-38,-38,-38,-38,-38
S,Dual,The dual lattice of L,0,1,0,0,0,0,0,0,0,LatMod,,LatMod,-38,-38,-38,-38,-38
S,PartialDual,The dual lattice of L,0,2,0,0,0,0,0,0,0,217,,0,0,LatMod,,LatMod,-38,-38,-38,-38,-38
S,Gerstein,"""The Gerstein reduction of L_p""",0,2,0,0,0,0,0,0,0,217,,0,0,LatMod,,LatMod,-38,-38,-38,-38,-38
S,DirectSum,The direct (orthogonal) of the lattices L1 and L2,0,2,0,0,0,0,0,0,0,LatMod,,0,0,LatMod,,LatMod,-38,-38,-38,-38,-38
A,RngOrd,1,APE
S,AbsolutePrimitiveElement,Returns an primitive element of R over the integers,0,1,0,0,0,0,0,0,0,215,,216,-38,-38,-38,-38,-38
S,ElementsOfNorm,Returns all elements of norm a in L up to sign,0,2,0,0,0,0,0,0,0,-45,,0,0,LatMod,,82,-38,-38,-38,-38,-38
S,OrthogonalDecomposition,Decomposes L into an orthogonal sum of indecomposables,0,1,0,0,0,0,0,0,0,LatMod,,82,-38,-38,-38,-38,-38
S,AutomorphismGroup,The automorphism group of the lattice L,0,1,0,0,0,0,0,0,0,LatMod,,178,-38,-38,-38,-38,-38
S,IsIsometric,Tests if the lattices L1 and L2 are isometric,0,2,0,0,0,0,0,0,0,LatMod,,0,0,LatMod,,36,-34,-38,-38,-38,-38
S,IsSimilar,Tests if the lattices L1 and L2 are similar,0,2,0,0,0,0,0,0,0,LatMod,,0,0,LatMod,,36,-34,-10,-38,-38,-38
S,IsSimilarGenus,Tests if the genera of L1 and L2 are similar,0,2,0,0,0,0,0,0,0,LatMod,,0,0,LatMod,,36,-38,-38,-38,-38,-38
S,Norm,The norm of the lattice L,0,1,0,0,0,0,0,0,0,LatMod,,324,-38,-38,-38,-38,-38
S,Scale,The scale of the lattice L,0,1,0,0,0,0,0,0,0,LatMod,,324,-38,-38,-38,-38,-38
S,Volume,The volume of the lattice L,0,1,0,0,0,0,0,0,0,LatMod,,324,-38,-38,-38,-38,-38
S,Determinant,The determinant of the free lattice L,0,1,0,0,0,0,0,0,0,LatMod,,28,-38,-38,-38,-38,-38
S,IsModular,"If L is modular, returns true and an ideal a such that a*Dual(L)=L",0,1,0,0,0,0,0,0,0,LatMod,,36,324,-38,-38,-38,-38
S,IsModular,"If L_p is p^v-modular, return true and v",0,2,0,0,0,0,0,0,0,217,,0,0,LatMod,,36,148,-38,-38,-38,-38
S,IsUnimodular,Returns true iff L_p is unimodular,0,2,0,0,0,0,0,0,0,217,,0,0,LatMod,,36,-38,-38,-38,-38,-38
S,IsUnimodular,Returns true iff L is unimodular,0,1,0,0,0,0,0,0,0,LatMod,,36,-38,-38,-38,-38,-38
S,IsSquarefree,Returns true iff L_p is squarefree,0,2,0,0,0,0,0,0,0,217,,0,0,LatMod,,36,-38,-38,-38,-38,-38
S,IsSquarefree,Returns true iff L is squarefree,0,1,0,0,0,0,0,0,0,LatMod,,36,-38,-38,-38,-38,-38
S,HasseInvariant,The Hasse invariant of L at p,0,2,0,0,0,0,0,0,0,217,,0,0,LatMod,,148,-38,-38,-38,-38,-38
S,HasseInvariant,The Hasse invariant of L at p,0,2,0,0,0,0,0,0,0,332,,0,0,LatMod,,148,-38,-38,-38,-38,-38
S,WittInvariant,The Witt invariant of L at p,0,2,0,0,0,0,0,0,0,217,,0,0,LatMod,,148,-38,-38,-38,-38,-38
S,WittInvariant,The Witt invariant of L at p,0,2,0,0,0,0,0,0,0,332,,0,0,LatMod,,148,-38,-38,-38,-38,-38
S,IsRationallyEquivalent,Tests if L1 and L2 are equivalent over the completion at p,0,3,0,0,0,0,0,0,0,217,,0,0,LatMod,,0,0,LatMod,,36,-38,-38,-38,-38,-38
S,IsRationallyEquivalent,Tests if L1 and L2 are equivalent over the completion at p,0,3,0,0,0,0,0,0,0,332,,0,0,LatMod,,0,0,LatMod,,36,-38,-38,-38,-38,-38
S,IsRationallyEquivalent,Tests if L1 and L2 are equivalent over their base field,0,2,0,0,0,0,0,0,0,LatMod,,0,0,LatMod,,36,-38,-38,-38,-38,-38
S,BadPrimes,The set of prime ideals at which L is not unimodular,0,1,0,0,0,0,0,0,0,LatMod,,83,-38,-38,-38,-38,-38
S,GenusSymbol,The genus symbol of L at p,0,2,0,0,0,0,0,0,0,217,,0,0,LatMod,,82,-38,-38,-38,-38,-38
S,IsLocallyIsometric,Returns true if and only if the p-adic completions of L1 and L2 are isometric,0,3,0,0,0,0,0,0,0,217,,0,0,LatMod,,0,0,LatMod,,36,-38,-38,-38,-38,-38
S,IsSameGenus,Returns true if and only if the lattices L1 and L2 are in the same genus,0,2,0,0,0,0,0,0,0,LatMod,,0,0,LatMod,,36,-38,-38,-38,-38,-38
S,JordanDecomposition,A Jordan decomposition of the completion of L at p,0,2,0,0,0,0,0,0,0,217,,0,0,LatMod,,82,82,82,-38,-38,-38
S,IsIsotropic,Tests if L is isotropic at p,0,2,0,0,0,0,0,0,0,217,,0,0,LatMod,,36,-38,-38,-38,-38,-38
S,IsIsotropic,Tests if L is isotropic at p,0,2,0,0,0,0,0,0,0,332,,0,0,LatMod,,36,-38,-38,-38,-38,-38
S,Neighbours,The p-neighbours of L,0,2,0,0,0,0,0,0,0,217,,0,0,LatMod,,82,-38,-38,-38,-38,-38
S,MaximalSublattices,The maximal sublattices of L that contain pL,0,2,0,0,0,0,0,0,0,217,,0,0,LatMod,,82,-38,-38,-38,-38,-38
S,Sublattices,The sublattices of index p^i in L that contain pL,0,3,0,0,0,0,0,0,0,148,,0,0,217,,0,0,LatMod,,82,82,-38,-38,-38,-38
S,MinimalSuperlattices,The minimal superlattices of L contained in p^-1 * L,0,2,0,0,0,0,0,0,0,217,,0,0,LatMod,,82,-38,-38,-38,-38,-38
S,IsMaximalIntegral,"Checks whether L is p-maximal integral. If not, a minimal integral over-lattice at p is returned",0,2,0,0,0,0,0,0,0,217,,0,0,LatMod,,36,LatMod,-38,-38,-38,-38
S,IsMaximalIntegral,"Checks whether L is maximal integral. If not, a minimal integral over-lattice is returned",0,1,0,0,0,0,0,0,0,LatMod,,36,LatMod,-38,-38,-38,-38
S,IsMaximal,Checks if L_p is Norm(L_p)-maximal,0,2,0,0,0,0,0,0,0,217,,0,0,LatMod,,36,LatMod,-38,-38,-38,-38
S,IsMaximal,Checks if L is Norm(L)-maximal,0,1,0,0,0,0,0,0,0,LatMod,,36,LatMod,-38,-38,-38,-38
S,MaximalIntegralLattice,A p-maximal integral lattice over L,0,2,0,0,0,0,0,0,0,217,,0,0,LatMod,,LatMod,-38,-38,-38,-38,-38
S,MaximalIntegralLattice,A maximal integral lattice containing L,0,1,0,0,0,0,0,0,0,LatMod,,LatMod,-38,-38,-38,-38,-38
S,MaximalIntegralLattice,A lattice which is maximal integral with respect to the quadratic form Q,0,1,0,0,0,0,0,0,0,-34,,LatMod,-38,-38,-38,-38,-38
S,^,internal,0,2,0,0,0,0,0,0,0,180,,0,0,LatMod,,LatMod,-38,-38,-38,-38,-38
S,LocalFactor,The local factor of L at the prime p in the Minkowsi-Siegel mass formula,0,2,0,0,0,0,0,0,0,217,,0,0,LatMod,,267,-38,-38,-38,-38,-38
S,Mass,Returns the mass of L,0,1,0,0,0,0,0,0,0,LatMod,,267,-38,-38,-38,-38,-38
S,HasseInvariant,The Hasse-Minkowski invariant of the quadratic form given by M at the place p,0,2,0,0,0,0,0,0,0,217,,0,0,177,,148,-38,-38,-38,-38,-38
S,HasseInvariant,The Hasse-Minkowski invariant of the quadratic form given by M at the place p,0,2,0,0,0,0,0,0,0,148,,0,0,177,,148,-38,-38,-38,-38,-38
S,QuadraticFormInvariants,The invariants describing the quadratic form M,1,0,1,177,0,-9,1,0,0,0,0,0,0,0,177,,-10,83,82,-38,-38,-38
S,QuadraticFormInvariants,The invariants describing the quadratic form M,1,0,1,177,0,262,1,0,0,0,0,0,0,0,177,,267,83,148,-38,-38,-38
S,MyQuaternionAlgebra,Returns a quaternion algebra only ramified at the places in P and S,2,0,1,82,0,217,1,1,82,0,332,2,0,0,0,0,0,0,0,82,,0,0,82,,17,-38,-38,-38,-38,-38
S,QuadraticFormWithInvariants,Computes a quadratic form of dimension Dim and determinant Det that has Hasse invariants -1 at the primes in Finite. The number of negative entries of the real signature is given in Negative,1,2,1,-52,0,148,4,0,0,0,0,0,0,0,148,,0,0,-52,,0,0,148,,0,0,148,,177,-38,-38,-38,-38,-38
S,QuadraticFormWithInvariants,Computes a quadratic form of dimension Dim and determinant Det that has Hasse invariants -1 at the primes in Finite. The number of negative entries of the real signature is given in Negative,1,2,1,-52,0,148,4,0,0,0,0,0,0,0,148,,0,0,-52,,0,0,267,,0,0,148,,177,-38,-38,-38,-38,-38
S,QuadraticFormWithInvariants,Computes a quadratic form of dimension Dim and determinant Det that has Hasse invariants -1 at the primes in Finite. The number of negative entries of the i-th real signature is given in Negative[i],2,2,1,-52,0,217,3,1,82,0,148,4,0,0,0,0,0,0,0,82,,0,0,-52,,0,0,-10,,0,0,148,,177,-38,-38,-38,-38,-38
S,IsLocallyIsotropic,,0,2,0,0,0,0,0,0,0,-1,,0,0,-1,,36,-38,-38,-38,-38,-38
S,IsIsotropic,"Checks if the quadratic form F is isotropic. If IsotropicVector is set to true, an isotropic vector is also returned",0,1,0,0,0,0,0,0,0,177,,36,160,-38,-38,-38,-38
S,QuadraticFormDecomposition,"Decompose F into an anisotropic kernel, an hyperbolic space and its radical",0,1,0,0,0,0,0,0,0,177,,159,159,159,-38,-38,-38
S,MaximalIsotropicSubspace,Returns a maximal totally isotropic subspace of F,0,1,0,0,0,0,0,0,0,177,,159,-38,-38,-38,-38,-38
S,AreEquivalentQuadraticForms,Returns a maximal totally isotropic subspace of F,2,0,1,177,0,262,1,1,177,0,262,2,0,0,0,0,0,0,0,177,,0,0,177,,36,177,-38,-38,-38,-38
S,AreEquivalentQuadraticForms,Returns a maximal totally isotropic subspace of F,2,0,1,177,0,-9,1,1,177,0,-9,2,0,0,0,0,0,0,0,177,,0,0,177,,boolElt,177,-38,-38,-38,-38
