from citation_record import CitationRecord

from axiom import Axiom_CitationItem
from ecm import ECM_CitationItem
from flint import FLINT_CitationItem
from frobby import Frobby_CitationItem
from gap import GAP_CitationItem
from gmp import GMP_CitationItem
from givaro import Givaro_CitationItem
from kash import KASH_CitationItem
from lie import LiE_CitationItem
from linbox import Linbox_CitationItem
from m4ri import M4RI_CitationItem
from mpfi import MPFI_CitationItem
from mpfr import MPFR_CitationItem
from macaulay2 import Macaulay2_CitationItem
from magma import Magma_CitationItem
from maple import Maple_CitationItem
from mathematica import Mathematica_CitationItem
from maxima import Maxima_CitationItem
from mupad import MuPAD_CitationItem
from ntl import NTL_CitationItem
from octave import Octave_CitationItem
from pari import PARI_CitationItem
from polybori import PolyBoRi_CitationItem
from r import R_CitationItem
from singular import Singular_CitationItem
from symmetrica import Symmetrica_CitationItem
from tachyon import Tachyon_CitationItem
from gfan import gfan_CitationItem
from ginac import ginac_CitationItem
from matlab import matlab_CitationItem
from mwrank import mwrank_CitationItem
from numpy import numpy_CitationItem
from povray import povray_CitationItem
from qsieve import qsieve_CitationItem
from scipy import scipy_CitationItem
