r"""
Neveu-Schwarz Super Vertex Algebra

The `N=1` or *Neveu-Schwarz* super vertex algebra is a super
extension of the Virasoro vertex algebra of central charge `c` with
generator `L` by an odd primary generator `G` of conformal weight
`3/2`. The remaining `\lambda`-bracket is given by:

.. MATH::

    [G_\lambda G] = 2L + \frac{\lambda^2 c}{3} |0\rangle.

AUTHORS:

- Reimundo Heluani (2020-06-09): Initial implementation.
"""

#******************************************************************************
#       Copyright (C) 2020 Reimundo Heluani <heluani@potuz.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#                  http://www.gnu.org/licenses/
#*****************************************************************************


from .universal_enveloping_vertex_algebra import \
                                                UniversalEnvelopingVertexAlgebra
from sage.sets.family import Family

class NeveuSchwarzVertexAlgebra(UniversalEnvelopingVertexAlgebra):
    def __init__(self,R,c=0):
        """
        The Neveu-Schwarz super vertex algebra.

        INPUT:

        - ``R`` -- a commutative ring; the base ring.
        - ``c`` -- an element of ``R`` (default: ``0``); the central
          charge.

        EXAMPLES:

        Some vectors in the `N=1` super vertex algebra of central
        charge `7/10`::

            sage: V = vertex_algebras.NeveuSchwarz(QQ,7/10)
            sage: M = V.get_weight(8)
            sage: [v.lift() for v in M.basis()]
            [L_-2L_-2L_-2L_-2|0>,
             L_-2L_-2G_-5/2G_-3/2|0>,
             L_-3L_-3L_-2|0>,
             L_-4L_-2L_-2|0>,
             L_-4G_-5/2G_-3/2|0>,
             L_-3G_-7/2G_-3/2|0>,
             L_-2G_-7/2G_-5/2|0>,
             L_-2G_-9/2G_-3/2|0>,
             L_-4L_-4|0>,
             L_-5L_-3|0>,
             L_-6L_-2|0>,
             G_-9/2G_-7/2|0>,
             G_-11/2G_-5/2|0>,
             G_-13/2G_-3/2|0>,
             L_-8|0>]

        A quotient by the ideal generated by the singular vector in
        conformal weight 4::

            sage: sing = V.find_singular(4); sing
            (L_-2L_-2|0> - 3/2*G_-5/2G_-3/2|0> + 3/10*L_-4|0>,)
            sage: Q = V.quotient(V.ideal(sing))
            sage: Q
            Quotient of The Neveu-Schwarz super vertex algebra of central charge 7/10 over Rational Field by the ideal generated by (L_-2L_-2|0> - 3/2*G_-5/2G_-3/2|0> + 3/10*L_-4|0>,)

        The Virasoro generator is nilpotent in the classical limit::

            sage: P = Q.classical_limit(); P.inject_variables()
            Defining L, G
            sage: L**2
            0
        """
        from sage.algebras.lie_conformal_algebras.\
             neveu_schwarz_lie_conformal_algebra import \
             NeveuSchwarzLieConformalAlgebra

        ML = NeveuSchwarzLieConformalAlgebra(R)
        cp = Family({ML.gen(2):c})
        super(NeveuSchwarzVertexAlgebra,self).__init__(R, ML,
                                                       central_parameters=cp)
        self._c = c

    def _repr_(self):
        """
        The name of this vertex algebra.

        EXAMPLES::

            sage: V = vertex_algebras.NeveuSchwarz(QQ,7/10); V
            The Neveu-Schwarz super vertex algebra of central charge 7/10 over Rational Field
        """
        return "The Neveu-Schwarz super vertex algebra of central charge {}"\
               " over {}".format(self.central_charge(),self.base_ring())



