r"""
Virasoro Vertex Algebra

The Virasoro Vertex algebra of central charge `c` is the `H`-graded
vertex algebra generated by a vector `L` of conformal weight `2` with
`\lambda`-bracket

.. MATH::

    [L_\lambda L] = T L + 2 \lambda L + \frac{\lambda^3}{12} c
    |0\rangle.

AUTHORS:

- Reimundo Heluani (2019-08-09): Initial implementation.
"""

#******************************************************************************
#       Copyright (C) 2019 Reimundo Heluani <heluani@potuz.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#                  http://www.gnu.org/licenses/
#*****************************************************************************


from .universal_enveloping_vertex_algebra import \
                                                UniversalEnvelopingVertexAlgebra
from sage.sets.family import Family

class VirasoroVertexAlgebra(UniversalEnvelopingVertexAlgebra):
    def __init__(self, R, c=0):
        r"""
        The universal Virasoro vertex algebra

        INPUT:

        - ``R`` -- a commutative ring; the base ring of this vertex
          algebra.

        - ``c`` -- an element of ``R`` (default: ``0``); the central
          charge of this vertex algebra.

        EXAMPLES::

            sage: V = VirasoroVertexAlgebra(QQ,1/2); V
            The Virasoro vertex algebra of central charge 1/2 over Rational Field
            sage: V.inject_variables()
            Defining L
            sage: L.nmodeproduct(L.T()*L,0)
            5*L_-3L_-2|0>
        """
        from sage.algebras.lie_conformal_algebras.\
             virasoro_lie_conformal_algebra import VirasoroLieConformalAlgebra
        ML = VirasoroLieConformalAlgebra(R)
        cp = Family({ML.gen(1):c})
        super(VirasoroVertexAlgebra,self).__init__(R, ML, central_parameters=cp)
        self._c = c

    def _repr_(self):
        """
        The name of this vertex algebra.

        EXAMPLES::

            sage: VirasoroVertexAlgebra(QQbar)
            The Virasoro vertex algebra of central charge 0 over Algebraic Field
        """
        return "The Virasoro vertex algebra of central charge {} over {}".\
                format(self.central_charge(),self.base_ring())



