cdef bint is_Expression(x)
cdef _repr_Expression(x)
cdef _latex_Expression(x)
cdef new_Expression(parent, x)
cdef new_Expression_from_pyobject(parent, x, bint force=?, bint recursive=?)
cdef new_Expression_wild(parent, unsigned int n=?)
cdef new_Expression_symbol(parent, name=?, latex_name=?, domain=?)
