name: Build & Test

on:
  push:
  workflow_dispatch:
    # Allow to run manually

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/sagemath/sage/sage-docker-ubuntu-focal-standard-with-targets:9.5
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup environment
        run: |
          # Populate SAGE_LOCAL based on the built SAGE_LOCAL contained in the Docker image 
          mv /sage/local local
          rm -Rf /sage/local
          ln -sf "$(pwd)"/local /sage/local
      
      - name: Build
        run: |
          ./bootstrap
          ./configure --enable-build-as-root
          make build
        env:
          MAKE: make -j2
          SAGE_NUM_THREADS: 2

      - name: Test
        run: ./sage -t --all -p0
