name: Build & Test

on:
  push:
  workflow_dispatch:
    # Allow to run manually

concurrency:
  # Cancel previous runs of this workflow for the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/sagemath/sage/sage-docker-ubuntu-focal-standard-with-targets:dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        run: |
          # Reuse built SAGE_LOCAL contained in the Docker image 
          ./bootstrap
          ./configure --enable-build-as-root --prefix=/sage/local --with-sage-venv --enable-editable
          # Install test tools
          ./venv/bin/python3 -m pip install coverage
      
      - name: Build
        run: make build
        env:
          MAKE: make -j2
          SAGE_NUM_THREADS: 2

      - name: Test
        run: |
          source ./bin/sage-env
          ../venv/bin/python3 -m coverage run ./bin/sage-runtests --all -p0
        working-directory: ./src

      - name: Prepare coverage results
        run: |
          ./venv/bin/python3 -m coverage combine src/.coverage/
          ./venv/bin/python3 -m coverage xml
      
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./src/coverage.xml
