name: windows-latest

on: [push]

jobs:
  cygwin:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: install cygwin with choco
      run: |
        choco --version
        choco install bash sed --source cygwin
    - name: install prerequisites with choco
      shell: bash {0}
      run: |
        PACKAGES=$(sed 's/#.*//;' ./build/pkgs/cygwin.txt ./build/pkgs/cygwin-bootstrap.txt)
        echo $PACKAGES
        choco install $PACKAGES --source cygwin
    - name: bootstrap
      shell: bash {0}
      run: |
        ./bootstrap
    - name: configure
      shell: bash {0}
      run: |
        ./configure || (cat config.log; exit 1)
    - name: make
      shell: bash {0}
      run: |
        MAKE="make -j8" make V=0
