name: windows-latest

on: [push]

jobs:
  cygwin:

    runs-on: windows-latest

    strategy:
      matrix:
        pkgs: [minimal, standard]

    steps:
    - uses: actions/checkout@v1
    - name: install cygwin with choco
      run: |
        choco --version
        choco install bash sed --source cygwin
    - name: install minimal prerequisites with choco
      shell: bash {0}
      run: |
        PACKAGES=$(sed 's/#.*//;' ./build/pkgs/cygwin.txt ./build/pkgs/cygwin-bootstrap.txt ./build/pkgs/*/distros/cygwin.txt)
        choco install $PACKAGES --source cygwin
    - name: install cygwin packages with choco
      if: matrix.pkgs == 'standard'
      shell: bash {0}
      run: |
        PACKAGES=$(sed 's/#.*//;' ./build/pkgs/*/distros/cygwin.txt)
        choco install $PACKAGES --source cygwin
    - name: bootstrap
      shell: /tools/cygwin/bin/bash {0}
      run: |
        ./bootstrap
    - name: configure
      shell: /tools/cygwin/bin/bash {0}
      run: |
        ./configure || (cat config.log; exit 1)
    - name: make
      shell: /tools/cygwin/bin/bash {0}
      run: |
        MAKE="make -j8" make V=0
