name: Build documentation

on:
  push:
  workflow_dispatch:
    # Allow to run manually

concurrency:
  # Cancel previous runs of this workflow for the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docs:
    runs-on: ubuntu-latest
    container: ghcr.io/sagemath/sage/sage-docker-ubuntu-focal-standard-with-targets:9.5
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        run: |
          # Reuse built SAGE_LOCAL contained in the Docker image 
          ./bootstrap
          ./configure --enable-build-as-root --prefix=/sage/local --with-sage-venv

      - name: Build
        run: make doc-html
        env:
          MAKE: make -j2
          SAGE_NUM_THREADS: 2

      - name: Copy docs
        run: |
          # For some reason the deploy step below cannot find /sage/...
          # So copy everything from there to local folder
          # We also need to replace the symlinks because netlify is not following them
          mkdir -p ./docs
          cp -r -L /sage/local/share/doc/sage/html/en/* ./docs

      - name: Deploy to Netlify preview
        id: deploy-neflify
        if: github.ref != 'refs/heads/master'
        uses: netlify/actions/cli@master
        with:
          # We could use  --alias="${NETLIFY_ALIAS}" to fix the deploy url to the branch name.
          # However, netlify currently doesn't support updates to a deploy with alias
          # https://github.com/netlify/cli/issues/948
          # https://github.com/netlify/cli/issues/1984
          # Note that even if this feature is implemented, one would also need to first process the branch name
          # to workaround the bug https://github.com/netlify/cli/issues/969.
          args: deploy --dir=docs
        env:
          NETLIFY_ALIAS: ${{ github.ref_name }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Deploy to Netlify production
        id: deploy-neflify
        if: github.ref == 'refs/heads/master'
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=docs --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Report deployment url
        run: |
          echo "::notice::The documentation has being automatically deployed to Netlify.\n\n✅ Preview: ${{ steps.deploy-neflify.outputs.NETLIFY_URL }}"
