name: Build documentation

on:
  push:
  workflow_dispatch:
    # Allow to run manually

concurrency:
  # Cancel previous runs of this workflow for the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docs:
    runs-on: ubuntu-latest
    container: ghcr.io/sagemath/sage/sage-docker-ubuntu-focal-standard-with-targets:9.5
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        run: |
          # Reuse built SAGE_LOCAL contained in the Docker image 
          ./bootstrap
          ./configure --enable-build-as-root --prefix=/sage/local --with-sage-venv

      - name: Build
        run: make doc-html
        env:
          MAKE: make -j2
          SAGE_NUM_THREADS: 2

      - name: Copy docs
        run: |
          # For some reason the deploy step below cannot find /sage/...
          # So copy everything from there to local folder
          mkdir -p ./docs
          cp -r /sage/local/share/doc/sage/html/en ./docs

      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        with: 
          args: deploy --dir=docs --alias="${NETLIFY_ALIAS}"
        env:
          NETLIFY_ALIAS: ${{ github.ref_name }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
