citation_items = {}
citation_items['PARI'] = ['sage.libs.pari', 'sage.interfaces.gp']
citation_items['Singular'] = ['sage.interfaces.singular', '_libsingular',
                       'sage.libs.singular']
citation_items['Maxima'] = ['sage.interfaces.maxima']
citation_items['GAP'] = ['sage.interfaces.gap']
citation_items['Magma'] = ['sage.interfaces.magma', 'sage.interfaces.magma_free']
citation_items['Axiom'] = ['sage.interfaces.axiom']
citation_items['ECM'] = ['sage.interfaces.ecm']
citation_items['scipy'] = ['scipy']
citation_items['numpy'] = ['numpy']
citation_items['ginac'] = ['sage.symbolic']
citation_items['Maple'] = ['sage.interfaces.maple']
citation_items['Mathematica'] = ['sage.interfaces.mathematica']
citation_items['MuPAD'] = ['sage.interfaces.mupad']
citation_items['Octave'] = ['sage.interfaces.octave']
citation_items['povray'] = ['sage.interfaces.povray']
citation_items['qsieve'] = ['sage.interfaces.qsieve']
citation_items['Macaulay2'] = ['sage.interfaces.macaulay2']
citation_items['mwrank'] = ['sage.interfaces.mwrank', 'sage.libs.mwrank']
citation_items['matlab'] = ['sage.interfaces.matlab']
citation_items['LiE'] = ['sage.interfaces.lie']
citation_items['Tachyon'] = ['sage.interfaces.tachyon']
citation_items['Frobby'] = ['sage.interfaces.frobby']
citation_items['gfan'] = ['sage.interfaces.gfan']
citation_items['R'] = ['sage.interfaces.r']
citation_items['KASH'] = ['sage.interfaces.kash']
citation_items['Linbox'] = ['sage.libs.linbox']
citation_items['Symmetrica'] = ['sage.libs.symmetrica']
citation_items['NTL'] = ['sage.libs.ntl',
                  'sage.rings.finite_rings.element_ntl_gf2e']
citation_items['FLINT'] = ['_flint']
citation_items['GMP'] = ['sage.rings.integer.Integer']
citation_items['MPFR'] = ['sage.rings.real_mpfr',
                   'sage.rings.complex_number']
citation_items['MPFI'] = ['sage.rings.real_mpfi',
                   'sage.rings.complex_interval']
citation_items['M4RI'] = ['sage.matrix.matrix_mod2_dense']
citation_items['Givaro'] = ['sage.rings.finite_rings.element_givaro']
citation_items['PolyBoRi'] = ['sage.rings.polynomial.pbori']
